- name: Install cert-manager
  hosts: localhost
  tasks:
    - name: Add Jetstack Helm repository
      community.kubernetes.helm_repository:
        name: jetstack
        repo_url: https://charts.jetstack.io
        state: present

    - name: Update Helm repositories
      community.kubernetes.helm_repository:
        name: jetstack
        state: updated

    - name: Install cert-manager
      community.kubernetes.helm:
        name: cert-manager
        chart: jetstack/cert-manager
        namespace: cert-manager
        create_namespace: true
        version: v1.18.2
        set:
          - installCRDs=true

    - name: Create ClusterIssuer for Let's Encrypt
      template:
        src: letsencrypt-clusterissuer.yaml.j2
        dest: /tmp/letsencrypt-clusterissuer.yaml

    - name: Apply ClusterIssuer
      kubernetes.core.k8s:
        state: present
        src: /tmp/letsencrypt-clusterissuer.yaml

    - name: Create Ingress for AWX
      template:
        src: awx-ingress.yaml.j2
        dest: /tmp/awx-ingress.yaml

    - name: Apply Ingress resource
      kubernetes.core.k8s:
        state: present
        src: /tmp/awx-ingress.yaml